### ISSUE TITLE
Tagged Release Checklist - 0.3.6 and 0.3.7

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1059]
- [x] Update the version in *package.json*
- [x] `npm i` to regenerate *package-lock.json*
- [x] `npm publish` to publish the version to [npm registry](https://npmjs.com).
- [x] Git annotated tag and push to Github
  - [x] `git tag -a v{version} -m "{your message}"` to create an annotated tag 
  - [x] `git push origin v{version}` to push up to the project's
   [releases](https://github.com/LD4P/sinopia_editor/releases)
- [x] Docker build and publish tagged Image, see See [documentation](https://github.com/LD4P/sinopia_editor/#building-latest-docker-image) for more information
  - [x] Build a tagged Docker image i.e. `docker build -t ld4p/sinopia_editor:{version} .`
  - [x] Push the tagged version to Dockerhub with `docker push ld4p/sinopia_editor:{version}`
- [x] Create Release notes for the tagged version on Github
- [x] Once tagged release is live on https://development.sinopia.io, this ticket will be assigned to the product owner who will approve the tagged release for deployment on
  - [ ] Staging at https://stage.sinopia.io/
  - [ ] Production at https://sinopia.io

**Comment by jermnelson** [comment]
@aaron-collier, can we close this ticket as it is absorbed into ticket #1078?
