### ISSUE TITLE
Improve lookups

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2166]
checked box means issue is resolved or a separate ticket has been created, or not really an issue, or unable to troubleshoot due to lack of information
- [x] 1. Geographic lookup: London and Tokyo are difficult to find, come up after scrolling through a long list (Issues: https://github.com/LD4P/qa_server/issues/248, https://github.com/LD4P/qa_server/issues/136)
- [x] 2. Performance: Faster QA lookups
- [x] 3. Wait state: if user has to wait more than a second, show a wait state (spinner) to indicate it's working (Issue: https://github.com/LD4P/sinopia_editor/pull/2567)
- [x] 4. Primary Contribution; Name of person did not show the name in the LOC all names (QA) list although it is established in NAF "Shinītī, Muḥammad al-Bashīr" . I copied and paste the URI http://id.loc.gov/authorities/names/n84070886.html but had this message "NetworkError when attempting to fetch resource"  . At the end I had to type the name in one of other boxes and used the compound characters table then pasted it  in Primary Contribution; Name of person and the disered result appeared!!.  (Issue: https://github.com/LD4P/qa_server/issues/201)
- [x] 4. Subject of the Work; No authority is found for the string Numidia--History!!  (Note: There isn't an LCSH URI for Numidia--History.) _(checking this off since if the LCSH URI doesn't exist, we can't find it)_
- [x] 5. Publication, Distribution, Manufacture, Production; name look up menu does not work for the publisher name "Muʼassasat Kunūz al-Ḥikmah lil-Nashr wa-al-Tawzīʻ" although it is the authorised form of the name. It appeared when searched in the original script but not all corporate names have references for the native form of the name in the authority (Issue: https://github.com/LD4P/qa_server/issues/201)
- [x] 6. Adding compund characters tables to Publication, Distribution, Manufacture, Production; name look up menu to ease the search. _if characters are missing from diacritic component, we now have a way for users to add. if a field should be a lookup but is not, need to talk to template owner_
- [x] 7. I had to enter "place of publication not identified in Publication "Place" under Publication, Distribution, Manufacture, Production; Bibeliunable to enter "Name" of publisher under Publication, Distribution, Manufacture, Production in Monograph Bibframe Work (Note: Not sure this is a lookup issue. Can't place of publication be ignore if there's no value? Or note this somewhere else in the template?) _if still a problem need to address with template owner_
- [x] 8. Language "Kwangali" did not come up when searching for language for Bibframe Work Instance; is in MARC language codes (Note: Where is the language list coming from? If we're talking about this template, https://sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested, it's not QA.) _need more info to troubleshoot_
- [x] 9. Lookup for the author did not show the authority URI. I had to input it as a new literal _cannot troubleshoot without knowing if this is an established URI and relevancy wasn't as desired, or was this a case where they needed to create a new name authority?_
- [x] 10. The LOC geographic name QA lookup still contains non-geographic entities, such as titles and organizations. (Issue: https://github.com/LD4P/qa_server/issues/248)
- [x] 11. In the LOC Names lookup, I needed to type in the names with the diacritics in order for QA to retrieve them. (Issue: https://github.com/LD4P/qa_server/issues/201)
- [x] effective LCNAF lookup in alphabetic order (Issue: https://github.com/LD4P/qa_server/issues/203)
- [x] 12. Couldn't get a name in contributor to show up in QA lookup in spite of the fact there was a NAR in NAF (Issues: https://github.com/LD4P/qa_server/issues/257, https://github.com/LD4P/qa_server/issues/239)
- [x] 13. If we have to enter diacritics to find the name in QA lookup, there has to be a diacritic input method for those fields. Currently there isn't. (Fixed: https://github.com/LD4P/sinopia_editor/issues/2652)
- [x] 14. String: personal name as a subject heading with basic subheading not authorized. _What is needed from Sinopia/QA here?_
- [x] Search without a proper diacritic just for the name failed.  Had to copy from a table from another field. Long responding time to find the authority.  (Issue: https://github.com/LD4P/qa_server/issues/201)
- [x] I keep getting "NetworkError when attempting to fetch resource" in QA lookups for names I know to be in id.loc.gov. It doesn't happen consistently and doesn't only happen when there are diacritics. The continued and inconsistent unreliability of QA, as well as how painfully slow it can be, is a gigantic problem. If we keep entering New Literals for names we know to exist in a vocabulary, how will reconciliation happen after-the-fact? Will we need to go back and manually add URIs at some point? (Note: we can't provide a lookup for thing that doesn't exist, for this need to establish it Sinopia or LC; Performance is being worked on through new indexing framework; Issue: https://github.com/LD4P/qa_server/issues/201)
- [x] 15. Lookup for LC subject headings did not work well, it took several attempts before it brought it up. I even tried unchecking/checking some of the boxes for other vocabularies. _Performance is being worked on through new indexing framework; unable to troubleshoot further without more information_
- [x] 16. Couldn't get lookup under place of capture to work. _unable to troubleshoot without more information_
- [x] Searching external authority files continues to be a problem. (Issue: https://github.com/LD4P/qa_server/issues/248)
- [x] In Sinopia Instance - when looking up a name in NAF it would be helpful to see the whole NAR. Sometimes seeing just the authorized form of the name is not enought to determine it if belogns to a particular instance - would be helpful to include the entire record for evaluation _we do show some context now, if more is needed, open a QA issue; also, not ideal, but once you select a name, you can click it and go directly to the authority record_
- [x] 17. Search results for names get direct URI, SKOS concept and MADS--we dont need the latter two to display and they resolve to the same URI if you click on them anyway.  Too much screen clutter, space could be better utilized by more info from the authority record. _is this still an issue? if so open QA ticket_
- [x] 18. LCNAF - ability to search by variant as well as official name (Note: they are, if we have examples where searches are failing we can add tests to make sure they are weighted properly.) _need examples of where this doesn't work in order to pursue_
- [x] 19. Searching external authority files continues to be a problem. _what problem specifically?_
- [x] 20. Predictability of search results and relevancy ranking are a mystery _we do have an open ticket to document how QA search works, which should help. need specific examples of where ranking and results are not as expected to troubleshoot_

**Comment by jimfhahn** [comment]
I'm noticing some specific lookup issues -- it seems when you search for a broad geographic city you end up with search results at the top that are specific regions within that city. It take a while to find the one you want. I wonder if the general term should show up first, not be buried lower in the list?

![image](https://user-images.githubusercontent.com/1310509/94299904-e5aaab00-ff2d-11ea-8c69-8b97731fcfa5.png)

Here I just want Chicago -- but I'm getting the first results various neighborhoods in Chicago. If I type it in like this Chicago (Ill.) then I get what I wanted to see, but I only typed it in that way after realizing how it is represented in LOC ID...

**Comment by jimfhahn** [comment]
If QA is loading -- should it have a loading indicator? otherwise I think the user may believe there are no results for their search...

**Comment by michelleif** [comment]
@sfolsom can you investigate Jim's feedback on geographic results?

@jimfhahn re loading indicator we are working on this! see #2182

**Comment by sfolsom** [comment]
FYI, I've added some links to issues for the concerns enumerated above. Some do not have enough detail to act on, but we'd be happy to discuss more to make sure we're addressing all issues.

**Comment by sfolsom** [comment]
Number 4. Non-established headings (constructed headings without URIs) will not show up in lookups. (Same with Number 14)
Number 

Number 8. I don't see Kwangali in the MARC language codes.

Number 16: Not sure what template this is referring to, but LC Geographics is working on the QA side.

**Comment by michelleif** [comment]
closing this ticket as the issues are either fixed or don't have enough info to troubleshoot
@jimfhahn if the geographic searching is still a problem, could you please open a new ticket in QA per https://github.com/LD4P/qa_server/issues/new?template=indexing_bug.md
