### ISSUE TITLE
UX issues listed by priority

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2309]
These are the issues identified as highest priority (in priority order) in Astrid's interviews with Sinopia users
- [x] ld4p/sinopia#292 change lookup UI to a modal instead of a dropdown (epic)
- [x] #2328 Convert layout from 3 columns to left nav with right panel
- [x] #2177 Text fields should be expandable
- [x] #2172 Allow user to view record before copying/editing
- [ ] #2178 user-friendly summary of record before saving (might be solved by #2172)
- [x] #2334 Save search even if user navigates away from search page
- [x] #2180 Remove need to clear cache and history
- [ ] #2189 upon log in go directly to Editor instead of staying on refreshed homepage
- [x] #2166 improve lookups (multiple items in this ticket)
- [x] #2084 add diacritic UI component to lookups (need to do #2175 first)
- [x] #2182 add wait state for searching that take longer than one second
- [x] #2168 personalized dashboard
- [ ] #2156 fielded and faceted advanced Sinopia search
- [x] #2164 validation (spellcheck, field-level based on value type, blank nodes)
- [x] #2171 keystrokes for diacritics
- [x] #2170 more efficient input for frequently used fields with same content
- [x] #2174 Allow browsing without creating RDF (decouple fxn from interaction)

**Comment by michelleif** [comment]
keeping this ticket open until issues are prioritized for WC4, then will close

**Comment by michelleif** [comment]
prioritization in process for WC4; this ticket reflected WC3 prioritization, so closing
