### ISSUE TITLE
Version 3.5.5 Tagged Release Checklist

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#2721]
- ~~Product owner assigned Release notes~~
  - ~~Updates `NewsItem.js` component.~~
  - ~~Sinopia [Wiki](https://github.com/LD4P/sinopia/wiki/Latest-Release,-What's-Next)~~
- [x] Create release.
  - [x] Pull latest master.
  - For the sinopia_editor only (sinopia_indexing_pipeline does not need to update the version number in the package.json file):
    - [x] Check out a branch and update the version in *package.json*
    - [x] `npm i` to regenerate *package-lock.json* (see note below)
    - [x] `npm publish` to publish the version to [npm registry](https://npmjs.com).
    - [x] Commit change to branch and push; create PR for version bump.  (You can't push directly to master, since it's a protected branch).
      - https://github.com/LD4P/sinopia_editor/pull/2722
    - [x] Once PR is merged, publish a [new release](https://github.com/LD4P/sinopia_editor/releases/new) with a version like `v1.0.2` and wait for Circleci to complete building and pushing docker images.
      - https://github.com/LD4P/sinopia_editor/releases/tag/v3.5.5
- [x] AWS Images for supporting projects - the Sinopia stack requires
  a number of other projects to run successfully both locally and on AWS. If any of
  these projects changed between tagged releases, you will need to update and tag the
  latest image on Dockerhub along with corresponding update to Terraform with the tagged
  release.
  - [x] Sinopia Indexing Pipeline https://github.com/LD4P/sinopia_indexing_pipeline
    - [x] Publish a [new release](https://github.com/LD4P/sinopia_indexing_pipeline/releases/new) with a version like `v1.0.2` and wait for Circleci to complete building and pushing docker images.
      - https://github.com/LD4P/sinopia_indexing_pipeline/releases/tag/v2.1.8
  - [x] Sinopia Exporter https://github.com/LD4P/sinopia_exporter
    - [x] Publish a [new release](https://github.com/LD4P/sinopia_exporter/releases/new) with a version like `v1.0.2` and wait for Circleci to complete building and pushing docker images.
      - https://github.com/LD4P/sinopia_exporter/releases/tag/v2.0.5
  - [x] Sinopia API https://github.com/LD4P/sinopia_api
    - [x] Publish a [new release](https://github.com/LD4P/sinopia_api/releases/new) with a version like `v1.0.2` and wait for Circleci to complete building and pushing docker images.
      - https://github.com/LD4P/sinopia_api/releases/tag/v1.1.7

- [x] Deploy to staging
  - [x] Follow [instructions](https://github.com/sul-dlss/terraform-aws/tree/master/organizations/staging/sinopia#deploying-a-release-to-staging) for pushing a release to staging. Make sure to update versions to Sinopia Editor, Sinopia Indexing Pipeline, Sinopia API, and Sinopia Exporter.
  - [x] Submit a new terraform PR.

- [ ] Product owner decides whether to deploy to production (which may not occur for every tagged release)
  - [x] Create a new terraform PR for production, making similar changes to staging.
  - [x] Request that Ops deploy to production.

  **NOTE**: if *package-lock.json* has links to unsecured http:// registries, try
  deleting *package-lock.json*, remove the node modules `rm -rf ./node_modules`,
  run `npm cache clean --force`, and then run `npm i --prefer-online`

**Comment by jmartin-sul** [comment]
docker images:
* https://hub.docker.com/layers/ld4p/sinopia_api/v1.1.7/images/sha256-f76e022035cd3ee62bb5cc7432bd6a422ec8658447779dc92be628beb7902e89?context=explore
* https://hub.docker.com/layers/ld4p/sinopia_exporter/v2.0.5/images/sha256-d4bc843417797217c2a117cbac5f7a82906411e8bbca8d4ab8263f05ab2285b6?context=explore
* https://hub.docker.com/layers/ld4p/sinopia_indexing_pipeline/v2.1.8/images/sha256-d96ccfe20cdca0e111b15f77552fd9b2aa77526d9f5834be18cea1aebf00738d?context=explore
* https://hub.docker.com/layers/ld4p/sinopia_editor/v3.5.5-stage/images/sha256-51149d4221985a09dad1d73558412348eff251375871037e393f261b7ed0c942?context=explore
* https://hub.docker.com/layers/ld4p/sinopia_editor/v3.5.5-prod/images/sha256-57a72494c09ddc5488d349c08852bcdf790fb22281e0bfb7e4209e530d9c384e?context=explore
