### ISSUE TITLE
move "base templates" from sinopia_api git repo / mongo_db deployment to locally loaded

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#3266]
Based on work for #2889 and #2907, there is a definite smell about the configuration for sinopia_editor UI living not only in mongo_db, but in LD4P/sinopia_api, a completely different code base from the rest of the editor.

LD4P/sinopia_api has a `setup` folder with json files that are used as "base templates" to get the sinopia_editor to display the correct UI widgets for editing a resource_template.

It might make more sense for these configurations to be local to the sinopia_editor codebase.

Tradeoffs:
#### Pros
- removes complexity from sinopia_api 
- puts "mongo-setup" docker-compose task for local development where it is needed
- keeps "configuration" for sinopia_editor closer to its use in ... sinopia_editor.
#### Cons
- effort required to make this change
- will add some "special case" complexity to sinopia_editor code when loading the "base templates" (look for "these 7 templates" locally, o.w. look in mongo)

Additional thoughts:
"base templates" --> 
- "bootstrap resource templates" ?  
- "bootup resource templates" ?  
- "template editor templates" ?  
- "initialization templates"

TO COMPLETE:
- [x] sinopia_editor has "base templates" and loads them from local files (see PR #3279)
- [x] sinopia_api no longer has "base template" files or "mongo_setup" in `docker-compose.yml` and may be able to drop some stuff in `package.json` (see PR LD4P/sinopia_api#217)
- [x] remove "base templates" from all the bastions (??)
- [x] consider different name for "base templates" that is more descriptive.
- [x] document what "base templates" are, how to modify, and what other steps are related (e.g. vocabulary documentation) ~~-- see https://github.com/LD4P/sinopia_editor/blob/editor-component-templates-doc/static/EditorComponentTemplates.md for a beginning.~~  (see PR #3306)

**Comment by ndushay** [comment]
"bootstrap template json"

**Comment by justinlittman** [comment]
"bootstrap" is a loaded term for me.

**Comment by ndushay** [comment]
"component template"  !!!

**Comment by ndushay** [comment]
I started some documentation on a branch:  https://github.com/LD4P/sinopia_editor/blob/editor-component-templates-doc/static/EditorComponentTemplates.md

**Comment by ndushay** [comment]
Have the base templates been removed from mongo for all environments?   That's the only thing left on this ticket.

**Comment by justinlittman** [comment]
@peetucket Using your new Mongo skills, can you delete the resource templates listed here: https://github.com/LD4P/sinopia_api/commit/4bd37da3a7025812feed35e2c823dee519674e86#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L133-L137 ?

Note that they will only be in the `resources` collection.

**Comment by peetucket** [comment]
> @peetucket Using your new Mongo skills, can you delete the resource templates listed here: [LD4P/sinopia_api@4bd37da#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L133-L137](https://github.com/LD4P/sinopia_api/commit/4bd37da3a7025812feed35e2c823dee519674e86#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L133-L137) ?
> 
> Note that they will only be in the `resources` collection.

1. These are all the templates in the PR in the "setup" folder?  (e.g. ` setup/rt_literal_property_attrs_doc.json`) 
2. Which sinopia environments to delete from?

**Comment by peetucket** [comment]
Note to self for remove syntax for a resource (using URI):

```
db.resources.remove({uri: 'http://localhost:3000/resource/FoobarTemplate'})
```

**Comment by justinlittman** [comment]
1. Yes.
2. All

**Comment by peetucket** [comment]
How to delete:

First verify we only deleting one each with the query:

```
db.resources.find({id: 'sinopia:template:property:literal'}).count()
db.resources.find({id: 'sinopia:template:property:lookup'}).count()
db.resources.find({id: 'sinopia:template:property'}).count()
db.resources.find({id: 'sinopia:template:property:resource'}).count()
db.resources.find({id: 'sinopia:template:resource'}).count()
db.resources.find({id: 'sinopia:template:uri'}).count()
db.resources.find({id: 'sinopia:template:property:uri'}).count()
```

Then delete with the same query:
```
db.resources.remove({id: 'sinopia:template:property:literal'})
db.resources.remove({id: 'sinopia:template:property:lookup'})
db.resources.remove({id: 'sinopia:template:property'})
db.resources.remove({id: 'sinopia:template:property:resource'})
db.resources.remove({id: 'sinopia:template:resource'})
db.resources.remove({id: 'sinopia:template:uri'})
db.resources.remove({id: 'sinopia:template:property:uri'})
```

**Comment by peetucket** [comment]
Deleted above seven resources from dev, stage and prod.

**Comment by justinlittman** [comment]
Thanks @peetucket !
