### ISSUE TITLE
follow on work for Amplify SDK session management

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#528]
follow on work from #460

- [x] update README to give new instructions for running test suite locally (explain that env vars are needed to provide the username and password for a valid cognito user in the dev user pool, since the integration tests do an actual login).  explain that login info for a test user can be obtained by asking another developer (so as to keep from posting login info in a public place, even if just for a test user).  (happened in #553)
- [x] ~~fix skipped tests in `__tests__/components/App.test.js` (which are about `App` component detecting whether user is logged in)~~ spawned #539 
- [x] ~~fix skipped tests in `__tests__/components/editor/ImportResourceTemplate.test.js` (which are about the component hitting Sinopia Server, which requires mocking some Cognito functionality)~~ spawned #539 
- [x] ~~` __tests__/components/LoginPanel.test.js`: test for display of authentication errors~~ spawned #560
- [x] ~~unit tests for CognitoUtils.js~~ spawned #561
- [x] ~~polish login form styling (`LoginPanel`)~~ spawned #562
- [x] ~~test new `mapStateToProps` and `mapDispatchToProps` functions~~ spawned #563
  - [x] ~~test `mapStateToProps` and `mapDispatchToProps` in `LoginPanel`~~
  - [x] ~~test `Editor`'s `mapStateToProps`~~
  - [x] ~~unit test for `ImportResourceTemplate.mapStateToProps`~~
- [x] ~~add functionality for dealing with authN/token errors (e.g. expired session) in `ImportResourceTemplate` component, test in `ImportResourceTemplate.test.js`~~ #564
- [x] ~~`Editor` should take `currentSession` as a prop, instead of the entirety of `authenticationState`~~ spawned #565
- [x] ~~`ImportResourceTemplate` should take subfields of auth state as props, instead of `authenticationState` as a whole~~ spawned #565
- [x] ~~no need for `.js` extensions on `CognitoUtils` imports (https://github.com/LD4P/sinopia_editor/pull/460#discussion_r285295044, https://github.com/LD4P/sinopia_editor/pull/460/#discussion_r285295713)~~ (spawned #566)

**Comment by jmartin-sul** [comment]
i am happy to start breaking off things from the above list as separate tickets, if we don't want to do all the above in one monolithic PR, or if we want to split up the work.

**Comment by jermnelson** [comment]
> i am happy to start breaking off things from the above list as separate tickets, if we don't want to do all the above in one monolithic PR, or if we want to split up the work.

Hi @jmartin-sul, I think creating specific Milestone 3 tickets out of this list would be good to surface this work in the Project Board.

**Comment by jmartin-sul** [comment]
since everything here has been broken off into more specific tickets, i'm going to go ahead and close this catch-all ticket.
